# Generated by Django 6.0.6 on 2026-06-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoredsite',
            name='interval_minutes',
        ),
        migrations.AddField(
            model_name='monitoredsite',
            name='crop_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitoredsite',
            name='crop_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitoredsite',
            name='crop_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitoredsite',
            name='crop_y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitoredsite',
            name='monitor_type',
            field=models.CharField(default='selector', max_length=20),
        ),
        migrations.AddField(
            model_name='monitoredsite',
            name='notify_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='monitoredsite',
            name='notify_telegram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monitoredsite',
            name='schedule_unit',
            field=models.CharField(default='hour', max_length=20),
        ),
        migrations.AddField(
            model_name='monitoredsite',
            name='schedule_value',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='monitoredsite',
            name='selected_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
