# Generated by Django 6.0.6 on 2026-07-12 12:53

import api.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_passwordresetcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='telegram_chat_id',
            field=api.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SiteCheckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('changed', models.BooleanField(default=False)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_logs', to='api.monitoredsite')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
    ]
