# Generated by Django 6.0.6 on 2026-07-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_userprofile_telegram_chat_id_sitechecklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoredsite',
            name='email_target',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='monitoredsite',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
