# Generated by Django 6.0.6 on 2026-07-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_monitoredsite_email_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoredsite',
            name='schedule_days',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='monitoredsite',
            name='schedule_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitoredsite',
            name='schedule_type',
            field=models.CharField(choices=[('interval', 'Interval (setiap X menit/jam)'), ('daily', 'Harian (jam tertentu)'), ('custom_days', 'Setiap N Hari (jam tertentu)'), ('weekly', 'Mingguan (hari + jam tertentu)')], default='interval', max_length=20),
        ),
    ]
