# Generated by Django 6.0.6 on 2026-07-18 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_activesession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActiveSession',
        ),
    ]
