# Generated by Django 6.0.6 on 2026-07-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_activesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitechecklog',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitechecklog',
            name='screenshot',
            field=models.FileField(blank=True, null=True, upload_to='snapshots/'),
        ),
    ]
