# Generated by Django 6.0.6 on 2026-07-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_sitechecklog_ai_summary_sitechecklog_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoredsite',
            name='schedule_unit',
            field=models.CharField(blank=True, default='hour', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='monitoredsite',
            name='schedule_value',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
