# Generated by Django 6.0.6 on 2026-08-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_emailverificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitechecklog',
            name='text_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
